import { existsSync, mkdirSync } from 'fs';
import path from 'path';
import { getLodyDataDir } from '@lody/shared/node/installation-profile';

import { getGhShimHostBinDir } from './gh-shim-script';
import {
  normalizeComparablePath,
  toSingleQuotedShellString,
  writeIfChanged,
} from './shell-file-utils';

const LODY_ZDOTDIR_PATH = path.join(getLodyDataDir(), 'zdotdir');

const buildInheritedSourceTarget = (
  filename: '.zshenv' | '.zprofile' | '.zshrc' | '.zlogin' | '.zlogout',
  inheritZdotdir: string | undefined,
  currentZdotdirPath: string
): string => {
  if (!inheritZdotdir) {
    return `$HOME/${filename}`;
  }

  if (normalizeComparablePath(inheritZdotdir) === normalizeComparablePath(currentZdotdirPath)) {
    return `$HOME/${filename}`;
  }

  return toSingleQuotedShellString(path.join(inheritZdotdir, filename));
};

const buildZshPassthroughSource = (
  filename: '.zshenv' | '.zshrc' | '.zlogin' | '.zlogout',
  inheritZdotdir: string | undefined,
  currentZdotdirPath: string
): string => {
  const inheritedTarget = buildInheritedSourceTarget(filename, inheritZdotdir, currentZdotdirPath);
  return `# Auto-generated by Lody for gh wrapper support.
if [ -f ${inheritedTarget} ]; then
  . ${inheritedTarget}
fi
`;
};

const buildZshenvSource = (
  inheritZdotdir: string | undefined,
  currentZdotdirPath: string
): string => buildZshPassthroughSource('.zshenv', inheritZdotdir, currentZdotdirPath);

const buildZprofileSource = (
  ghShimBinDir: string,
  inheritZdotdir: string | undefined,
  currentZdotdirPath: string
): string => {
  const inheritedTarget = buildInheritedSourceTarget(
    '.zprofile',
    inheritZdotdir,
    currentZdotdirPath
  );
  return `# Auto-generated by Lody for gh wrapper support.
if [ -f ${inheritedTarget} ]; then
  . ${inheritedTarget}
fi

export PATH=${toSingleQuotedShellString(ghShimBinDir)}:"$PATH"
`;
};

export const shouldInjectZdotdirForGhShim = (): boolean =>
  process.platform === 'darwin' && (existsSync('/bin/zsh') || existsSync('/usr/bin/zsh'));

export const ensureLodyZdotdirForGhShim = (
  inheritZdotdir?: string,
  brokerStateFilePath?: string
): string => {
  const zdotdirPath = brokerStateFilePath
    ? path.join(getGhShimHostBinDir(brokerStateFilePath), 'zdotdir')
    : LODY_ZDOTDIR_PATH;
  mkdirSync(zdotdirPath, { recursive: true });

  writeIfChanged(path.join(zdotdirPath, '.zshenv'), buildZshenvSource(inheritZdotdir, zdotdirPath));
  writeIfChanged(
    path.join(zdotdirPath, '.zprofile'),
    buildZprofileSource(getGhShimHostBinDir(brokerStateFilePath), inheritZdotdir, zdotdirPath)
  );
  writeIfChanged(
    path.join(zdotdirPath, '.zshrc'),
    buildZshPassthroughSource('.zshrc', inheritZdotdir, zdotdirPath)
  );
  writeIfChanged(
    path.join(zdotdirPath, '.zlogin'),
    buildZshPassthroughSource('.zlogin', inheritZdotdir, zdotdirPath)
  );
  writeIfChanged(
    path.join(zdotdirPath, '.zlogout'),
    buildZshPassthroughSource('.zlogout', inheritZdotdir, zdotdirPath)
  );

  return zdotdirPath;
};
