import { mkdirSync } from 'fs';
import path from 'path';
import { getLodyDataDir } from '@lody/shared/node/installation-profile';

import { getGhShimHostBinDir } from './gh-shim-script';
import {
  normalizeComparablePath,
  toSingleQuotedShellString,
  writeIfChanged,
} from './shell-file-utils';

const LODY_BASH_ENV_PATH = path.join(getLodyDataDir(), 'bashenv');

const buildBashEnvSource = (
  ghShimBinDir: string,
  inheritBashEnv: string | undefined,
  currentBashEnvPath: string
): string => {
  const shouldSourceInherited =
    inheritBashEnv &&
    normalizeComparablePath(inheritBashEnv) !== normalizeComparablePath(currentBashEnvPath);
  const sourceInherited = shouldSourceInherited
    ? `if [ -f ${toSingleQuotedShellString(inheritBashEnv)} ]; then
  . ${toSingleQuotedShellString(inheritBashEnv)}
fi

`
    : '';

  return `# Auto-generated by Lody for gh wrapper support.
${sourceInherited}export PATH=${toSingleQuotedShellString(ghShimBinDir)}:"$PATH"
`;
};

export const shouldInjectBashEnvForGhShim = (): boolean => process.platform !== 'win32';

export const ensureLodyBashEnvForGhShim = (
  inheritBashEnv?: string,
  brokerStateFilePath?: string
): string => {
  const bashEnvPath = brokerStateFilePath
    ? path.join(getGhShimHostBinDir(brokerStateFilePath), 'bashenv')
    : LODY_BASH_ENV_PATH;
  mkdirSync(path.dirname(bashEnvPath), { recursive: true });
  writeIfChanged(
    bashEnvPath,
    buildBashEnvSource(getGhShimHostBinDir(brokerStateFilePath), inheritBashEnv, bashEnvPath)
  );
  return bashEnvPath;
};
